spring:
  main:
    banner-mode: off
  application:
    name: desafioDev
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3308/gestao_de_curso
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate.format_sql: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

server:
  port: 8080

